# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OverlapClipper
                                 A QGIS plugin
 This modules clips features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-02
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Benjamin Dadson
        email                : benjamindadson32@gmail.com
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QButtonGroup, QTreeWidgetItem

# Initialize Qt resources from file resources.py
from .resources import *  # noqa: F401, F403

# Import the code for the DockWidget
from .overlap_clipper_dockwidget import OverlapClipperDockWidget, DialogWindow
from .algorithms import clean_overlap, get_feature_area
from .algorithms import clean_geometry_artifacts

import os.path
from qgis.core import QgsApplication, QgsFeatureRequest, Qgis, QgsWkbTypes
from itertools import combinations

from qgis import processing


class OverlapClipper:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.provider = None

        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "OverlapClipper_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr("&Overlap Clipper")
        self.toolbar = self.iface.addToolBar("OverlapClipper")
        self.toolbar.setObjectName("OverlapClipper")

        self.pluginIsActive = False
        self.dockwidget = None
        self.layer = None

        self.loadAlgorithms()

    def loadAlgorithms(self):
        """Register the custom processing provider and its algorithms."""
        from .providers import OverlapProvider

        self.provider = OverlapProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate("OverlapClipper", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.toolbar.addAction(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ":/plugins/overlap_clipper/icon.png"
        self.add_action(
            icon_path,
            text=self.tr("Overlap Clipper"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        if self.dockwidget:
            self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Overlap Clipper"), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

        if self.provider is not None:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None

    def run(self):
        """Run method that loads and starts the plugin"""
        if not self.pluginIsActive:
            self.pluginIsActive = True

            if self.dockwidget is None:
                self.layer = self.iface.activeLayer()
                layer = self.layer
                self.dockwidget = OverlapClipperDockWidget()
                dw = self.dockwidget

                dw.clipButton.clicked.connect(self.do_clip)
                dw.overlapTableButton.clicked.connect(  # noqa: E501
                    self.generate_overlap_table
                )
                self.button_group = QButtonGroup(dw)
                self.button_group.addButton(dw.firstSelected)
                dw.firstSelected.clicked.connect(
                    lambda: self.change_overlap_option(dw.firstSelected)
                )
                self.button_group.addButton(dw.largest)
                dw.largest.clicked.connect(
                    lambda: self.change_overlap_option(dw.largest)
                )
                self.button_group.addButton(dw.smallest)
                dw.smallest.clicked.connect(
                    lambda: self.change_overlap_option(dw.smallest)
                )

                if self.layer:
                    dw.treeWidget.setHeaderLabel(layer.name())
                self.populate_treewidget()

                self.selection_order = []
                self.overlap_option = "First"

                self.iface.layerTreeView().currentLayerChanged.connect(
                    self.on_active_layer_changed
                )

                if self.layer:
                    _sig = self.layer.selectionChanged
                    _sig.connect(self.track_selection_order)

            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def log_message(self, message, level=0):
        """
        Helper function to show logs on the screen (QGIS message bar).
        level: 0=Info, 1=Warning, 2=Critical
        """
        levels = {
            0: ("OverlapClipper Info", Qgis.MessageLevel.Info, 5),
            1: ("OverlapClipper Warning", Qgis.MessageLevel.Warning, 5),
            2: ("OverlapClipper Error", Qgis.MessageLevel.Critical, 10),
        }
        title, qgis_level, duration = levels.get(
            level, ("OverlapClipper Info", Qgis.MessageLevel.Info, 5)
        )
        self.iface.messageBar().pushMessage(
            title, message, level=qgis_level, duration=duration
        )
        print(f"OverlapClipper Log: {message}")

    def pair_features(self):
        """
        Generates pairs of features that overlap and need to be processed.
        Implements the new logic based on the
        'Edit all intersecting features' checkbox.

        Returns:
            list: A list of (fid1, fid2) tuples
            representing the pairs to process.
        """
        if not self.layer:
            return []

        selected_features = self.layer.selectedFeatures()
        if not selected_features:
            self.log_message("No features selected!", 1)
            return []

        dlg = self.dockwidget
        edit_selection_only = dlg.check_edit_selection_only.isChecked()

        if edit_selection_only:
            if len(selected_features) < 2:
                _msg = "Please select at least two features to process."
                self.log_message(_msg, 1)
                return []

            fids_to_process = [f.id() for f in selected_features]

        else:
            features_to_process = {f.id(): f for f in selected_features}
            _layer = self.layer
            _qfr = QgsFeatureRequest

            for selected_feat in selected_features:
                bbox = selected_feat.geometry().boundingBox()
                request = _qfr().setFilterRect(bbox)

                for feature in _layer.getFeatures(request):
                    if feature.id() in features_to_process:
                        continue

                    try:
                        _g = selected_feat.geometry()
                        if feature.geometry().intersects(_g):
                            features_to_process[feature.id()] = feature
                    except Exception as e:
                        self.log_message(
                            f"Error checking intersection for "
                            f"feature {feature.id()}: {e}",
                            1,
                        )

            fids_to_process = list(features_to_process.keys())

            if len(fids_to_process) < 2:
                self.log_message(
                    "Less than two features found for processing "
                    "(selected + intersecting).",
                    1,
                )
                return []

        if self.overlap_option == "First":
            fids_sorted = self.sort_selection_order(fids_to_process)
        else:
            fids_sorted = self.sort_fids_by_area(fids_to_process)
            if self.overlap_option == "Largest":
                fids_sorted.reverse()

        fid_combinations = list(combinations(fids_sorted, 2))

        overlapping_combinations = []

        def _get_feat(fid):
            return next(self.layer.getFeatures(QgsFeatureRequest(fid)), None)

        for f_id1, f_id2 in fid_combinations:
            try:
                feature1 = _get_feat(f_id1)
                feature2 = _get_feat(f_id2)

                if (
                    feature1
                    and feature2
                    and feature1.geometry()
                    and feature2.geometry()
                ):
                    if feature1.geometry().intersects(feature2.geometry()):
                        overlapping_combinations.append((f_id1, f_id2))
            except Exception as e:
                _err = "Error checking overlap between %s and %s: %s" % (
                    f_id1,
                    f_id2,
                    e,
                )
                self.log_message(_err, 2)

        if not overlapping_combinations:
            self.log_message("No overlapping feature pairs found.", 0)
            return []

        return overlapping_combinations

    def do_clip(self):
        """Executes the main overlap cleaning process."""
        if not self.layer:
            return

        if self.layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            return

        if not self.layer.isEditable():
            self.layer.startEditing()

        try:
            fid_combinations = self.pair_features()
        except Exception as e:
            _err = f"An error occurred during feature pairing: {e}"
            self.log_message(_err, 2)
            return

        if not fid_combinations:
            return

        processed_count = 0
        for f_id1, f_id2 in fid_combinations:
            if self.modify_features(f_id1, f_id2):
                processed_count += 1

        dlg = self.dockwidget
        if processed_count > 0:
            enable_undo = dlg.check_enable_undo.isChecked()
            if enable_undo:
                self.log_message(
                    f"Successfully clipped {processed_count} "
                    f"feature pairs. Changes committed.",
                    0,
                )
            else:
                try:
                    self.layer.commitChanges()
                    self.log_message(
                        f"Successfully clipped {processed_count} "
                        f"feature pairs. Changes committed.",
                        0,
                    )
                except Exception as e:
                    _msg = "Failed to commit changes: %s. Rolling back." % e
                    self.log_message(_msg, 2)
                    self.layer.rollBack()
        else:
            self.layer.rollBack()
            self.log_message("No features were modified.", 0)

        self.layer.removeSelection()
        self.populate_treewidget()

    def modify_features(self, f_id1, f_id2):
        """
        Applies the overlap cleaning logic for a single pair of features.
        f_id1 is the feature that maintains its geometry (clipper).
        f_id2 is the feature that gets clipped (clipped).

        Returns:
            bool: True if feature2 was modified and updated, False otherwise.
        """
        layer = self.layer

        try:
            feature1 = next(layer.getFeatures(QgsFeatureRequest(f_id1)), None)
            feature2 = next(layer.getFeatures(QgsFeatureRequest(f_id2)), None)

            if not feature1 or not feature2:
                self.log_message(
                    f"Could not retrieve features with IDs "
                    f"{f_id1} or {f_id2}. Skipping pair.",
                    1,
                )
                return False

            geom1 = feature1.geometry()
            geom2 = feature2.geometry()

            if geom1.isNull() or geom2.isNull():
                self.log_message(
                    f"One or both features ({f_id1}, {f_id2}) "
                    f"have null geometry. Skipping.",
                    1,
                )
                return False

            geom1 = clean_geometry_artifacts(geom1)
            geom2 = clean_geometry_artifacts(geom2)

            if geom1.intersection(geom2).area() <= 0:
                return False

            modified_geom2 = clean_overlap(geom2, geom1)

            if modified_geom2.equals(geom2):
                _m = "Feature %s was not modified by clipping with %s." % (
                    f_id2,
                    f_id1,
                )
                self.log_message(_m, 0)
                return False

            feature2.setGeometry(modified_geom2)

            if not layer.updateFeature(feature2):
                _m = "Failed to update feature %s." % (f_id2)
                _m += " in the layer's edit buffer."
                self.log_message(_m, 2)
                return False

            return True

        except Exception as e:
            self.log_message(
                f"An unexpected error occurred while modifying "
                f"features {f_id1} and {f_id2}: {e}",
                2,
            )
            return False

    # --- Utility methods ---

    def track_selection_order(self, added, removed, changed):
        """Triggered when selection changes."""
        self.populate_treewidget()

        for fid in added:
            if fid not in self.selection_order:
                self.selection_order.append(fid)

        for fid in removed:
            if fid in self.selection_order:
                self.selection_order.remove(fid)

    def sort_selection_order(self, current_selection_fids):
        """
        Sorts FIDs based on the original selection order,
        placing unselected but intersecting features at the end.
        """
        selection_order_set = set(self.selection_order)
        current_selection_set = set(current_selection_fids)

        in_selection_order = [
            fid for fid in current_selection_set if fid in selection_order_set
        ]

        _not_selected = current_selection_set - selection_order_set
        not_in_selection_order = list(_not_selected)

        in_selection_order_sorted = sorted(
            in_selection_order,
            key=lambda x: self.selection_order.index(x),
        )

        result = in_selection_order_sorted + not_in_selection_order
        return result

    def sort_fids_by_area(self, fid_list):
        """
        Sorts FIDs by the area of their geometries in ascending order.
        """
        layer = self.layer
        if not layer or not fid_list:
            return []

        fid_area_list = []
        for fid in fid_list:
            feature = next(layer.getFeatures(QgsFeatureRequest(fid)), None)
            if feature:
                area = get_feature_area(feature)
                fid_area_list.append((fid, area))

        sorted_fid_area_list = sorted(fid_area_list, key=lambda x: x[1])
        sorted_fid_list = [fid for fid, area in sorted_fid_area_list]

        return sorted_fid_list

    def change_overlap_option(self, radioButton):
        if radioButton.isChecked():
            self.overlap_option = radioButton.text().split()[0]

    def populate_treewidget(self):
        """
        Populates the QTreeWidget with selected features
        and handles UI state.
        """
        treewidget = self.dockwidget.treeWidget
        treewidget.clear()

        layer = self.layer
        if not layer:
            treewidget.setHeaderLabel("No Active Layer")
            return

        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            _label = f"Layer: {layer.name()} (Not Polygon)"
            treewidget.setHeaderLabel(_label)
            return

        treewidget.setHeaderLabel(f"Layer: {layer.name()}")

        selected_features = layer.selectedFeatures()
        if not selected_features:
            return

        for feature in selected_features:
            fid_str = f"Feature ID: {feature.id()}"
            feature_item = QTreeWidgetItem(treewidget)
            feature_item.setText(0, fid_str)

            attributes = feature.attributes()
            fields = layer.fields()

            for idx, field in enumerate(fields):
                field_name = field.name()
                field_value = attributes[idx]
                attribute_item = QTreeWidgetItem(feature_item)
                attribute_item.setText(0, f"{field_name}: {field_value}")

    def on_active_layer_changed(self, new_layer):
        """
        Updates the plugin state when the active layer changes.
        """
        if self.layer and hasattr(self.layer, "selectionChanged"):
            try:
                _sig = self.layer.selectionChanged
                _sig.disconnect(self.track_selection_order)
            except (TypeError, RuntimeError):
                pass

        self.layer = new_layer
        self.clear_selection_order()

        is_polygon_layer = False
        if new_layer and new_layer.isValid():
            try:
                if new_layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                    is_polygon_layer = True
            except AttributeError:
                pass

        dlg = self.dockwidget
        dlg.clipButton.setEnabled(is_polygon_layer)
        dlg.overlapTableButton.setEnabled(is_polygon_layer)
        dlg.firstSelected.setEnabled(is_polygon_layer)
        dlg.largest.setEnabled(is_polygon_layer)
        dlg.smallest.setEnabled(is_polygon_layer)
        dlg.check_edit_selection_only.setEnabled(is_polygon_layer)
        dlg.check_enable_undo.setEnabled(is_polygon_layer)

        self.populate_treewidget()

        if is_polygon_layer:
            if hasattr(self.layer, "selectionChanged"):
                _sig = self.layer.selectionChanged
                _sig.connect(self.track_selection_order)
        else:
            self.dockwidget.treeWidget.setHeaderLabel("Select a Polygon Layer")

    def clear_selection_order(self):
        """Clears the current selection order."""
        self.selection_order = []

    def open_dialog(self):
        """Create and show the dialog window."""
        dialog = DialogWindow(self.dockwidget)
        dialog.exec_()

    def generate_overlap_table(self):
        alg = QgsApplication.processingRegistry().algorithmById(
            "overlap_clipper_provider:generateoverlaptable"
        )
        if alg is None:
            _msg = "Algorithm not found. Make sure it is registered."
            self.log_message(_msg, 2)
            return

        processing.execAlgorithmDialog(alg)
