# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OverlapClipperDockWidget
                                 A QGIS plugin
 This modules clips features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-02
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Benjamin Dadson
        email                : benjamindadson32@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

_dir = os.path.dirname(__file__)
ui_base = os.path.join(_dir, "overlap_clipper_dockwidget_base.ui")
FORM_CLASS, _ = uic.loadUiType(ui_base)


class OverlapClipperDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(OverlapClipperDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()


FORM_CLASS2, _ = uic.loadUiType(ui_base)


class DialogWindow(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(DialogWindow, self).__init__(parent)
        dialog_ui = os.path.join(os.path.dirname(__file__), "dialog.ui")
        uic.loadUi(dialog_ui, self)
